### ISSUE TITLE
Admin page detect ImageMagick

### ISSUE THREAD

**Issue by Pross** [Lorti/dominant-colors-lazy-loading-wordpress-plugin#1]
At the moment the admin page does not attempt to detect ImageMagick and so when the user clicks the Calculate button nothing happens except every pending image says Error next to it.

**Comment by Pross** [comment]
https://github.com/Lorti/dominant-colors-lazy-loading-wordpress-plugin/pull/2

**Comment by Lorti** [comment]
Fixed by #2 and some additional changes in 6b277c4954fb9b5bc92cc33966d051aa26316fde. 
Live as [0.5.1](https://plugins.trac.wordpress.org/browser/dominant-colors-lazy-loading/tags/0.5.1) in the WordPress SVN.
Thanks, @Pross and @pedro-mendonca!
