### ISSUE TITLE
List of files that can't be calculated.

### ISSUE THREAD

**Issue by pedro-mendonca** [Lorti/dominant-colors-lazy-loading-wordpress-plugin#13]
Hi @Lorti 

It would be nice to list the files that can't be calculated below the error message **"All attempts seem to have failed. Please make sure that the attachment files exist."**

If there is a problem with some files, knowing it's names would be considerably better because give the user the oportunity to check them. This is better than just have a permanent message of some vague errors.

This list already appeared in a previous version of the plugin, and gave me the oportunity to check some files. Now it's just a less helpfull error message.

**Comment by Lorti** [comment]
I think a link to the attachment in the media library may also be helpful, instead of just printing the ID and name of the attachment.

**Comment by pedro-mendonca** [comment]
Yep, that would be even better :)

**Comment by Lorti** [comment]
Cheers! 🍻

**Comment by pedro-mendonca** [comment]
Working great :)
Thanks!
