### ISSUE TITLE
Dominate color remains in trasparent portion of rendered PNG

### ISSUE THREAD

**Issue by ManderZander** [Lorti/dominant-colors-lazy-loading-wordpress-plugin#18]
Dominant Colors Lazy Loading Version 0.6.0 
WordPress Version 4.6.1

The source PNG has about 50% transparency:
http://sparkacting.com/wp-content/uploads/2016/09/2016-clockwork-alchemy-logo-214x237.png

The Dominant Colors Lazy rendered image still shows the dominant color:
http://sparkacting.com/wp-content/uploads/2016/09/Dominant-Colors-Lazy-Loading-Bug-report-2016-09-30-crop.png

Source html from WordPress post:
`<img class="alignright size-full wp-image-207" src="http://sparkacting.com/wp-content/uploads/2016/09/2016-clockwork-alchemy-logo-214x237.png" alt="2016-clockwork-alchemy-logo-214x237" width="214" height="237" />`

Html the browser is rendering (note the added style="background: #622016;" ):
`<img class="alignleft size-full wp-image-207 dcll-image" src="http://sparkacting.com/wp-content/uploads/2016/09/2016-clockwork-alchemy-logo-214x237.png" style="background: #622016;" alt="2016-clockwork-alchemy-logo-214x237" width="214" height="237" data-pagespeed-url-hash="267363157" onload="pagespeed.CriticalImages.checkImageForCriticality(this);">`

**Comment by ManderZander** [comment]
I only encountered this issue when is configured to Dominant Colors Lazy Loading us the "SVG" format. As a work around I've switch Dominant Colors Lazy Loading to use GIF.

**Comment by Lorti** [comment]
Hello @ManderZander, version 0.6.1 should fix your issue! 🙂

**Comment by ManderZander** [comment]
Verified: the bug is gone. Thanks :-)
