### ISSUE TITLE
Switch to using lazysizes

### ISSUE THREAD

**Issue by curtchan** [Lorti/dominant-colors-lazy-loading-wordpress-plugin#26]
Lazysizes is a Google-suggested library for lazyloading, tested it on non-WP website and the usage is very simple, you just have to set proper class on element that you want to lazyload and it will work out of the box (takes care of both data-src and data-srcset).
So it shouldn't be hard to rewrite to make use of it.

https://github.com/aFarkas/lazysizes

**Comment by Lorti** [comment]
What problems that you have with the Dominant Colors Lazy Loading Wordpress Plugin does this solve?
