### ISSUE TITLE
Can't activate plugin

### ISSUE THREAD

**Issue by pedro-mendonca** [Lorti/dominant-colors-lazy-loading-wordpress-plugin#6]
Hi,

I'm having trouble in activating the plugin. In some installs it says I don't have ImageMagick, while the hosting service is telling me I have.

In other cases I can't even activate it, giving me this fatal error message:

> **Parse error**: syntax error, unexpected '[', expecting ')' in (...)**/wp-content/plugins/dominant-colors-lazy-loading/public/class-dominant-colors-lazy-loading-public.php** on line **266**

I have the current WordPress 4.5.1 and the plugin version 0.5.1

**Comment by Lorti** [comment]
The parse error seems to refer to the `[]` array literal. Are you running something older than PHP 5.4? I can change the literals right way, but we'll further have to investigate the ImageMagick problem... What are the results if you run a simple script testing for `extension_loaded('imagick')` and `class_exists('Imagick')` on your server?

**Comment by pedro-mendonca** [comment]
I'm on PHP 5.6.19.

Here are the results of those functions:
`extension_loaded('imagick')` -> FALSE
`class_exists('Imagick')` -> FALSE

Something is wrong here, but it's probably on the hosting side.

**Comment by Lorti** [comment]
I have released a new version with your translation and `array()` style literals. Can you activate it then on some of your installs?

Thank you a lot for testing different environments, much appreciated. I will close this issue if you don't mind, as it seems to be a problem with your hosting. Feel free to reopen if you have new information!

**Comment by pedro-mendonca** [comment]
I have two setups:
The one that was failing activation is on PHP 5.3.29.
This one I can already activate with this update you've made! Thanks :+1: 

The one I'm having ImageMagick problems is on PHP 5.6.19. This one I'm still investigating with the hosting.

**Comment by pedro-mendonca** [comment]
Yes, this issue is closed!
Thanks :)
