### ISSUE TITLE
Not all media file types should be used by the plugin

### ISSUE THREAD

**Issue by pedro-mendonca** [Lorti/dominant-colors-lazy-loading-wordpress-plugin#7]
Hi,

I'm testing the plugin in a library with different types of files, at least I have JPG and PDF.

The PDF isn't parsed by the plugin, and this expected.
The problem is that the PDF is listed as a parsable file and listed in the error list after the _Calculate_
I believe this could be corrected by filtering out PDFs, or the oposite, giving a finite list of the file types that can be calculated by the plugin. In this case, probably the file type list should be documented in the settings page, and probably also the file list to process should include the files extensions.

**Comment by Lorti** [comment]
You are right, the recalculation in the settings page needs rethinking and some work. This is tied to #5.

**Comment by pedro-mendonca** [comment]
This not a malfunction, is just a false positive error, that needs some polishement :+1:

**Comment by Lorti** [comment]
Thank you for both the hint and the pull request, only image mime types are now supported.

**Comment by pedro-mendonca** [comment]
Hi @Lorti 
One more thing, if you want I can open a new issue. When there are some files that can't be calculated, they don't appear listed, which makes it more dificult to find what files need to be checked manually.

**Comment by Lorti** [comment]
I figured that the fallback can handle those files, as one can not fix what Imagick can't process. You would have to reupload them differently. But yes, open an issue (enhancement) if you want. Should only need a few small changes :-)

**Comment by pedro-mendonca** [comment]
Ok.
I do find it usefull because I found a case where it can serve as debug. If a file isn't found, than something can be fixed somewhere, and it's a good idea to know wwich files rather than just a permanent number of resistent files not calculable.
Thanks, I'll open an issue with this than.
