### ISSUE TITLE
skips every other image on load

### ISSUE THREAD

**Issue by eminozlem** [Lorti/dominant-colors-lazy-loading-wordpress-plugin#9]
I wanted to use it in woocommerce product thumbnails but it seems to be skipping every other image for me for some reason. When i console.log( image ) - the images with .lazy class-, it does indeed skip the image at dom level eventhough the image has the "lazy" class.
When you scroll / resize, they load fine as expected, but not onload.
Havent tried it with regular post thumbnails but i believe the result would be same.

Working link : [http://egeev.com/urun-kategori/oturma-odasi/](url) ( for now at least, might disable it later if i cant figure it out )

Screenshot:
![eeclipboard01](https://cloud.githubusercontent.com/assets/507708/15083312/2aa78212-13d5-11e6-9181-6b163d171edb.jpg)

Code used:

```
remove_action( 'woocommerce_before_shop_loop_item_title', 'woocommerce_template_loop_product_thumbnail', 10);
add_action( 'woocommerce_before_shop_loop_item_title', 'woocommerce_template_loop_product_thumbnail', 10);

if ( ! function_exists( 'woocommerce_template_loop_product_thumbnail' ) ) {
    function woocommerce_template_loop_product_thumbnail() {
        echo woocommerce_get_product_thumbnail();
    }
}
if ( ! function_exists( 'woocommerce_get_product_thumbnail' ) ) {
    function woocommerce_get_product_thumbnail( $size = 'shop_catalog', $placeholder_width = 0, $placeholder_height = 0  ) {
        global $post, $woocommerce;
        if ( has_post_thumbnail() ) {
           $image = get_the_post_thumbnail( $post->ID, $size );
           return apply_filters( 'dominant_colors', $image, get_post_thumbnail_id ( $post->ID) );
        }
         elseif ( wc_placeholder_img_src() ) {
           return wc_placeholder_img( $size );
        }
    }
}
```

I dont think I have any other plugins that could conflict
![plgclipboard01](https://cloud.githubusercontent.com/assets/507708/15083558/956075a4-13d6-11e6-8cfa-0e821090fdd6.jpg)

**Comment by Lorti** [comment]
Has this been fixed for you with https://github.com/Lorti/dominant-colors-lazy-loading-wordpress-plugin/commit/d28a2f113d0836abb862938626f0953aedda8175 and Version 0.5.4?

**Comment by eminozlem** [comment]
Yup, much better. Every other image thing is solved. But as you can see in the screenshot, the 3rd -bottom- row not loaded, despite the fact that they are in the viewport
![s9clipboard01](https://cloud.githubusercontent.com/assets/507708/15098509/0762a9a2-1548-11e6-9a67-3395be7141f1.jpg)

**Comment by Lorti** [comment]
Your page is jumping when a square placeholder is replaced with the original image, this may be the issue, although it is just a guess. Have you tried using the SVG placeholders or setting the correct aspect ratio via CSS on the placeholders? Also what environment are we talking about? Latest Firefox on Windows 7?

**Comment by eminozlem** [comment]
Yup changing to SVG solved it. It was the same both on Firefox and Chrome on Win7
